import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar/Navbar";
import Sidebar from "./components/Sidebar/Sidebar";
import { ThemeProvider } from "./src/Providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
        <body className="min-h-screen flex flex-col text-white dark:text-white transition-colors duration-300">
          <ThemeProvider>
          <div className="fixed inset-0 bg-gradient-to-br
    from-indigo-400 via-sky-300 to-indigo-400
    dark:from-fuchsia-900 dark:dark:via-slate-950 dark:to-violet-900">
            <Navbar />
            <div className="min-h-screen flex">
              <Sidebar />
              <main className="flex-1 p-8">
              {children}
              </main>
            </div>
          </div>
          </ThemeProvider>
        </body>
    </html>
  );
}
